### ISSUE TITLE
This implementation does not appear to be compliant with the reference implementation

### ISSUE THREAD

**Issue by nebulaeonline** [skeeto/isaac64#1]
I know this is an old project, but people are probably always looking for a fast PRNG.

I'll leave it up to people much smarter than I am to determine if Isaac64 is suitable as a crypto RNG, but people, please use your best judgement.

That being said, your implementation does not output numbers that jive with that which can be generated from the original C implementation by Bob Jenkins: https://[burtleburtle.net/bob/c/isaac64.c](https://burtleburtle.net/bob/c/isaac64.c

It does not match the expected output published by the Rust project here: https://docs.rs/rand_isaac/latest/src/rand_isaac/isaac64.rs.html#84

It also does not match the expected output published by Zig here: https://github.com/ziglang/zig/blob/master/lib/std/rand/Isaac64.zig

I am fairly new to go, and Isaac64 is kind of my go to.  If I did something wrong, I apologize.

**Comment by skeeto** [comment]
The core of ISAAC64, including all its security properties, is its state 
permutation. My shuffle() behaves identically to the original isaac64(). 
Load identical states, run ISAAC64 on it, and the new states and output 
buffer will be identical. That's how I got the test vectors. I just tried 
it again manually, and everything still lines up.

The catch is loading identical states. I chose custom seeding (splitmix64) 
because the original "fill with messy stuff" isn't great, especially on 
machines with fast multiplication (i.e. anything running Go). It's slower 
and more complex than it needs to be, and I saw no reason to use it. The 
core ISAAC64 permutation does not mix its state well, and so relies on a 
good starting state, which is probably why seeding is so complicated. The 
permutation clearly has too few rounds to really be secure, though that's 
also why it's so fast.

On revisit, and looking at it with more experience, I'm unimpressed. Using 
a mostly-zero input state, contrast the results with 8 rounds of Chacha20, 
and it's a world of difference. ISAAC64 probably tests well by brute force 
of its enormous 2kiB state, which hides its deficiencies.

**Comment by nebulaeonline** [comment]
Thank you for the detailed response, I appreciate. it.

I have always avoided ISAAC64 (and the original 32-bit) for anything related to cryptography because it has had very little actual cryptanalysis performed on it.  That always scared me, despite Bob's page being up for ages and his $1,000 reward for actual attacks.

That being said, its speed is why it works so well as an actual PRNG as opposed to a CSRNG, and that's my use case.

I'm just always apprehensive when I see repos that claim conformance that cannot be (quickly) verified with Bob's original C code.

Take care
